/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedEmpleadosRouteImport } from './routes/_authenticated/empleados'
import { Route as AuthenticatedFacturacionRouteImport } from './routes/_authenticated/facturacion'
import { Route as AuthenticatedLibroRegistrosRouteImport } from './routes/_authenticated/libro-registros'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPiscinasRouteImport } from './routes/_authenticated/piscinas'
import { Route as AuthenticatedRutasRouteImport } from './routes/_authenticated/rutas'
import { Route as RegistroTokenRouteImport } from './routes/registro.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpleadosRoute = AuthenticatedEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturacionRoute =
  AuthenticatedFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibroRegistrosRoute =
  AuthenticatedLibroRegistrosRouteImport.update({
    id: '/libro-registros',
    path: '/libro-registros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiscinasRoute = AuthenticatedPiscinasRouteImport.update({
  id: '/piscinas',
  path: '/piscinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRutasRoute = AuthenticatedRutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RegistroTokenRoute = RegistroTokenRouteImport.update({
  id: '/registro/$token',
  path: '/registro/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-registros': typeof AuthenticatedLibroRegistrosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/piscinas': typeof AuthenticatedPiscinasRoute
  '/rutas': typeof AuthenticatedRutasRoute
  '/registro/$token': typeof RegistroTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/libro-registros': typeof AuthenticatedLibroRegistrosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/piscinas': typeof AuthenticatedPiscinasRoute
  '/rutas': typeof AuthenticatedRutasRoute
  '/registro/$token': typeof RegistroTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/empleados': typeof AuthenticatedEmpleadosRoute
  '/_authenticated/facturacion': typeof AuthenticatedFacturacionRoute
  '/_authenticated/libro-registros': typeof AuthenticatedLibroRegistrosRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/piscinas': typeof AuthenticatedPiscinasRoute
  '/_authenticated/rutas': typeof AuthenticatedRutasRoute
  '/registro/$token': typeof RegistroTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracion'
    | '/empleados'
    | '/facturacion'
    | '/libro-registros'
    | '/panel'
    | '/piscinas'
    | '/rutas'
    | '/registro/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracion'
    | '/empleados'
    | '/facturacion'
    | '/libro-registros'
    | '/panel'
    | '/piscinas'
    | '/rutas'
    | '/registro/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracion'
    | '/_authenticated/empleados'
    | '/_authenticated/facturacion'
    | '/_authenticated/libro-registros'
    | '/_authenticated/panel'
    | '/_authenticated/piscinas'
    | '/_authenticated/rutas'
    | '/registro/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegistroTokenRoute: typeof RegistroTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empleados': {
      id: '/_authenticated/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion': {
      id: '/_authenticated/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AuthenticatedFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro-registros': {
      id: '/_authenticated/libro-registros'
      path: '/libro-registros'
      fullPath: '/libro-registros'
      preLoaderRoute: typeof AuthenticatedLibroRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/piscinas': {
      id: '/_authenticated/piscinas'
      path: '/piscinas'
      fullPath: '/piscinas'
      preLoaderRoute: typeof AuthenticatedPiscinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rutas': {
      id: '/_authenticated/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof AuthenticatedRutasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/registro/$token': {
      id: '/registro/$token'
      path: '/registro/$token'
      fullPath: '/registro/$token'
      preLoaderRoute: typeof RegistroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedEmpleadosRoute: typeof AuthenticatedEmpleadosRoute
  AuthenticatedFacturacionRoute: typeof AuthenticatedFacturacionRoute
  AuthenticatedLibroRegistrosRoute: typeof AuthenticatedLibroRegistrosRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPiscinasRoute: typeof AuthenticatedPiscinasRoute
  AuthenticatedRutasRoute: typeof AuthenticatedRutasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedEmpleadosRoute: AuthenticatedEmpleadosRoute,
  AuthenticatedFacturacionRoute: AuthenticatedFacturacionRoute,
  AuthenticatedLibroRegistrosRoute: AuthenticatedLibroRegistrosRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPiscinasRoute: AuthenticatedPiscinasRoute,
  AuthenticatedRutasRoute: AuthenticatedRutasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegistroTokenRoute: RegistroTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
